[project]
name = "modeltools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "onnx>=1.17.0",
    "onnxruntime>=1.19.2",
    "torch>=2.5.0",
    "transformers>=4.45.2",
]
